pool:
  vmImage: 'ubuntu-latest'

steps:
- task: Docker@2
  condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/master'))
  inputs:
    containerRegistry: 'rtuitlab connection by admin'
    repository: 'rtuitlab/geohelper-back'
    command: 'buildAndPush'
    Dockerfile: 'Dockerfile'
    buildContext: '.'
    tags: |
      $(Build.BuildId)
      latest
    addPipelineData: false